name = "ParticlesMC"
uuid = "98828e2c-de49-11ef-324d-d77a22de11e4"
version = "0.1.0"

[deps]
Arianna = "07692032-97b4-4f8d-80d7-e18df88d31a9"
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Aqua = "0.8"
Arianna = "0.1"
Comonicon = "1.0"
ComponentArrays = "0.15"
ConcreteStructs = "0.2"
DataStructures = "0.18"
DelimitedFiles = "1.9"
Distributions = "0.25"
LinearAlgebra = "1.9"
Printf = "1.9"
StaticArrays = "1.9"
Statistics = "1.9"
TOML = "1"
Test = "1.9"
julia = "1.9"
Pkg = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[targets]
test = ["Test", "DelimitedFiles", "Aqua", "Pkg"]
